src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"items","categories","orders"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Groups({"items","categories","orders"})
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Groups({"items","categories"})
     * @Assert\PositiveOrZero
     */
    private $menu_position;

    /**
     * @ORM\Column(type="boolean", options={"default"=true})
     * @Groups({"items"})
     * @Assert\NotNull
     */
    private $active;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Groups({"items"})
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Groups({"items"})
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Item::class, mappedBy="category", orphanRemoval=true)
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMenuPosition(): ?int
    {
        return $this->menu_position;
    }

    public function setMenuPosition(int $menu_position): self
    {
        $this->menu_position = $menu_position;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new \DateTimeImmutable();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAt(): self
    {
        $this->updatedAt = new DateTimeImmutable();

        return $this;
    }

    /**
     * @return Collection<int, Item>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setCategory($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getCategory() === $this) {
                $item->setCategory(null);
            }
        }

        return $this;
    }
}

src/Controller/API/CategoryController.php
<?php

namespace App\Controller\API;

use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoryController extends AbstractController
{
    /**
     * @Route("/api/categories", name="app_api_category_list")
     */
    public function list(CategoryRepository $categoryRepository): JsonResponse
    {
        //  récupérer les categories
        $categories = $categoryRepository->findBy(['active' => true], ['menu_position' => 'ASC', 'name' => 'ASC']);

        // on retour les catégories en json
        return $this->json($categories, Response::HTTP_OK, [], ["groups" => "categories"]);
    }
}

src/Controller/Back/CategoryController.php
<?php

namespace App\Controller\Back;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/back/category")
 */
class CategoryController extends AbstractController
{
    /**
     * @Route("/", name="app_back_category_list", methods={"GET"})
     */
    public function list(CategoryRepository $categoryRepository): Response
    {
        $categories = $categoryRepository->findBy([], ['menu_position' => 'ASC', 'name' => 'ASC']);
        
        return $this->render('back/category/list.html.twig', [
            'categories' => $categories,
        ]);
    }

    /**
     * @Route("/new", name="app_back_category_new", methods={"GET", "POST"})
     */
    public function new (Request $request, CategoryRepository $categoryRepository): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            return $this->redirectToRoute('app_back_category_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/category/new.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_category_show", methods={"GET"})
     */
    public function show(Category $category): Response
    {
        return $this->render('back/category/show.html.twig', [
            'category' => $category,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_back_category_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            return $this->redirectToRoute('app_back_category_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/category/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_category_delete", methods={"POST"})
     */
    public function delete(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $category->getId(), $request->request->get('_token'))) {
            $categoryRepository->remove($category, true);
        }

        return $this->redirectToRoute('app_back_category_list', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/ClosedOrderController.php
<?php

namespace App\Controller\Back;

use App\Entity\ClosedOrder;
use App\Form\ClosedOrderType;
use App\Repository\ClosedOrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/back/closed/order")
 */
class ClosedOrderController extends AbstractController
{
    /**
     * @Route("/", name="app_back_closed_order_list", methods={"GET"})
     */
    public function list(ClosedOrderRepository $closedOrderRepository): Response
    {

        return $this->render('back/closed_order/list.html.twig', [
            'closed_orders' => $closedOrderRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_back_closed_order_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ClosedOrderRepository $closedOrderRepository): Response
    {
        $closedOrder = new ClosedOrder();
        $form = $this->createForm(ClosedOrderType::class, $closedOrder);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $closedOrderRepository->add($closedOrder, true);

            return $this->redirectToRoute('app_back_closed_order_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/closed_order/new.html.twig', [
            'closed_order' => $closedOrder,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_closed_order_show", methods={"GET"})
     */
    public function show(ClosedOrder $closedOrder): Response
    {
        return $this->render('back/closed_order/show.html.twig', [
            'closed_order' => $closedOrder
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_back_closed_order_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ClosedOrder $closedOrder, ClosedOrderRepository $closedOrderRepository): Response
    {
        $form = $this->createForm(ClosedOrderType::class, $closedOrder);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $closedOrderRepository->add($closedOrder, true);

            return $this->redirectToRoute('app_back_closed_order_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/closed_order/edit.html.twig', [
            'closed_order' => $closedOrder,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_closed_order_delete", methods={"POST"})
     */
    public function delete(Request $request, ClosedOrder $closedOrder, ClosedOrderRepository $closedOrderRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $closedOrder->getId(), $request->request->get('_token'))) {
            $closedOrderRepository->remove($closedOrder, true);
        }

        return $this->redirectToRoute('app_back_closed_order_list', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/ItemController.php
<?php

namespace App\Controller\Back;

use App\Entity\Item;
use App\Form\ItemType;
use App\Repository\ItemRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/back/item")
 */
class ItemController extends AbstractController
{
    /**
     * @Route("/", name="app_back_item_list", methods={"GET"})
     */
    public function list(ItemRepository $itemRepository): Response
    {
        return $this->render('back/item/list.html.twig', [
            'items' => $itemRepository->findAllSortByMenuPosition(),
        ]);
    }

    /**
     * @Route("/new", name="app_back_item_new", methods={"GET", "POST"})
     */
    public function new (Request $request, ItemRepository $itemRepository): Response
    {
        $item = new Item();
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemRepository->add($item, true);

            return $this->redirectToRoute('app_back_item_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/item/new.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_item_show", methods={"GET"})
     */
    public function show(Item $item): Response
    {
        return $this->render('back/item/show.html.twig', [
            'item' => $item,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_back_item_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Item $item, ItemRepository $itemRepository): Response
    {
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemRepository->add($item, true);

            return $this->redirectToRoute('app_back_item_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/item/edit.html.twig', [
            'item' => $item,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_item_delete", methods={"POST"})
     */
    public function delete(Request $request, Item $item, ItemRepository $itemRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $item->getId(), $request->request->get('_token'))) {
            $itemRepository->remove($item, true);
        }

        return $this->redirectToRoute('app_back_item_list', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/MainController.php
<?php

namespace App\Controller\Back;

use App\Repository\CategoryRepository;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mercure\Discovery;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/back")
 */
class MainController extends AbstractController
{

    /**
     * @Route("/", name="app_back_home")
     */
    public function home(CategoryRepository $categoryRepository)
    {
        $categoriesToDisplay = $categoryRepository->findBy(['active' => true], ['menu_position' => 'ASC', 'name' => 'ASC']);

        return $this->render("back/main/home.html.twig", [
            'categories' => $categoriesToDisplay,
        ]);
    }

    /**
     * @Route("/kitchen", name="app_back_kitchen")
     */
    public function kitchen(OrderRepository $orderRepository)
    {
        $ordersToDisplay = $orderRepository->findAllByStatusOne();
        $orderItems = [];
        foreach ($ordersToDisplay as $order) {
            $orderItems[] = $order->getOrderItems();
        }
        return $this->render("back/main/kitchen.html.twig", [
            'orders' => $ordersToDisplay,
            'orderItems' => $orderItems
        ]);
    }

    /**
     * @Route("/discover", name="app_back_discover")
     */
    public function discover(Request $request, Discovery $discovery): JsonResponse
    {
        // Link: <https://hub.example.com/.well-known/mercure>; rel="mercure"
        $discovery->addLink($request);

        return $this->json([
            'message' => 'done!',
        ]);
    }

    /**
     * @Route("/publish", name="app_back_publish")
     */
    // public function publish(HubInterface $hub): Response
    // {
    //     $update = new Update(
    //         'http://localhost/apo-Order/projet-8-o-commande-back/public/api/orders',
    //         json_encode(['message' => 'hello world!'])
    //     );

    //     $hub->publish($update);

    //     return new Response('published!');
    // }

}

src/Controller/Back/OrderController.php
<?php

namespace App\Controller\Back;

use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/back/order")
 */
class OrderController extends AbstractController
{
    /**
     * @Route("/", name="app_back_order_list", methods={"GET"})
     */
    public function list(OrderRepository $orderRepository): Response
    {
        return $this->render('back/order/list.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

}

src/Controller/Back/SecurityController.php
<?php
namespace App\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 * @Route("/back")
 */
class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_back_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('back/security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/logout", name="app_back_logout")
     */
    public function logout()
    {
        return $this->redirectToRoute('app_back_home');
    }
}

templates/back/category/_delete_form.html.twig
<form method="post" action="{{ path('app_back_category_delete', { id: category.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}" />
  <button class="btn btn-danger btn-sm mx-1 mb-2 bi bi-trash"> Delete</button>
</form>

templates/back/category/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-warning btn-sm mx-1 mb-2 bi bi-save">{{ button_label|default(' Create') }}</button>
{{ form_end(form) }}

templates/back/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Edit Category
{% endblock %}

{% block body %}
<div class="container-fluid">
  <h1>Edit Category</h1>

  {{ include('back/category/_form.html.twig', { button_label: ' Update' }) }}

  {{ include('back/category/_delete_form.html.twig') }}

  <a href="{{ path('app_back_category_list') }}"><button type="button" class="btn btn-sm btn-primary mx-1 mb-2 bi bi-arrow-left-square"> Back to list</button></a>

  </div>
{% endblock %}

templates/back/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Category List
{% endblock %}

{% block body %}
  <div>
    <h1>Category List</h1>
    <button type="button" onclick="window.location.href='{{ path('app_back_category_new') }}';" class="btn btn-success bi bi-plus-lg"></button>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Menu Position</th>
        <th>Active</th>
        <th>Created</th>
        <th>Updated</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <td>{{ category.id }}</td>
          <td>{{ category.name }}</td>
          <td>{{ category.menuPosition }}</td>
          <td>{{ category.active ? 'Yes' : 'No' }}</td>
          <td>{{ category.createdAt ? category.createdAt|date('Y-m-d H:i:s') : '' }}</td>
          <td>{{ category.updatedAt ? category.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
          <td>
            <button type="button" onclick="window.location.href='{{ path('app_back_category_show', { id: category.id }) }}';" class="btn btn-primary btn-sm bi bi-list"></button>
            <button type="button" onclick="window.location.href='{{ path('app_back_category_edit', { id: category.id }) }}';" class="btn btn-warning btn-sm bi bi-pencil-square"></button>
          </td>
        </tr>
      {% else %}
        <tr>
          <td colspan="7">no records found</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/back/category/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Category List
{% endblock %}
{% block categoryActive %}
  active
{% endblock %}
{% block body %}
  <div class="container-fluid">
    <div>
      <h1>Category List</h1>
      <a href="{{ path('app_back_category_new') }}"><button type="button" class="btn btn-primary mb-3 bi bi-plus-lg"></button></a>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Menu Position</th>
          <th>Name</th>
          <th>Active</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for category in categories %}
          <tr>
            <td>{{ category.menuPosition }}</td>
            <td>{{ category.name }}</td>            
            <td>{{ category.active ? 'Yes' : 'No' }}</td>
            <td>
              <a href="{{ path('app_back_category_show', { id: category.id }) }}"><button type="button" class="btn btn-info btn-sm bi bi-eye"></button></a>
              <a href="{{ path('app_back_category_edit', { id: category.id }) }}"><button type="button" class="btn btn-warning btn-sm bi bi-pencil-square"></button></a>
            </td>
          </tr>
        {% else %}
          <tr>
            <td colspan="7">No records found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/back/category/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  New Category
{% endblock %}

{% block body %}
  <div class="container-fluid">
    <h1>Create new Category</h1>

    {{ include('back/category/_form.html.twig') }}

    <a href="{{ path('app_back_category_list') }}"><button type="button" class="btn btn-sm btn-primary mx-1 mb-2 bi bi-arrow-left-square">Back to list</button></a>
  </div>
{% endblock %}

templates/back/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Category
{% endblock %}

{% block body %}
<div class="container-fluid">
  <h1>Category</h1>

  <table class="table">
    <tbody>
      <tr>
        <th>Name</th>
        <td>{{ category.name }}</td>
      </tr>
      <tr>
        <th>Menu_position</th>
        <td>{{ category.menuPosition }}</td>
      </tr>
      <tr>
        <th>Active</th>
        <td>{{ category.active ? 'Yes' : 'No' }}</td>
      </tr>
      <tr>
        <th>CreatedAt</th>
        <td>{{ category.createdAt ? category.createdAt|date('Y-m-d H:i:s') : '' }}</td>
      </tr>
      <tr>
        <th>UpdatedAt</th>
        <td>{{ category.updatedAt ? category.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
      </tr>
    </tbody>
  </table>

  

  <a href="{{ path('app_back_category_edit', { id: category.id }) }}"><button type="button" class="btn btn-sm btn-warning mx-1 mb-2 bi bi-pencil-square"> Edit</button></a>

  {{ include('back/category/_delete_form.html.twig') }}

  <a href="{{ path('app_back_category_list') }}"><button type="button" class="btn btn-sm btn-primary mx-1 mb-2 bi bi-arrow-left-square"> Back to list</button></a>
</div>
{% endblock %}